
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";

import StoreWrapper from "@/store/wrapper";
import DemoContextProvider from "../context/demoContext";
import SocketContextProvider from "../context/socketContext";

import { QueryClientProvider } from "@tanstack/react-query";
import { queryClient } from "../query/index";

import Navbar from "@/components/Navbar";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";
import ErrorCard from "@/components/ErrorCard";
import UserContextProvider from "@/context/userContext";

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <QueryClientProvider client={queryClient}>
          <SocketContextProvider>
            <StoreWrapper>
              <DemoContextProvider>
                <UserContextProvider>
                  <body
                    className={cn(
                      "min-h-screen bg-background font-sans antialiased",
                      fontSans.variable
                      )}
                      >
                    <Navbar />
                    {children}
                    <ErrorCard />
                  </body>
                </UserContextProvider>
              </DemoContextProvider>
            </StoreWrapper>
          </SocketContextProvider>
        </QueryClientProvider>
      </ClerkProvider>
    </html>
  );
}
